### ISSUE TITLE
Prismic previews?

### ISSUE THREAD

**Issue by kkor** [birkir/gatsby-source-graphql-universal#2]
Since you're redirecting from https://github.com/birkir/gatsby-plugin-prismic-preview to here, do you happen to have an example of how to setup gatsby-source-graphql-universal to work with Prismic previews?

**Comment by birkir** [comment]
I actually redirect to https://github.com/birkir/gatsby-source-prismic-graphql not here

There are demos in the readme

**Comment by kkor** [comment]
Aaah, that explains some things, my bad :'D
I'll take a look at the repo, takk!

**Comment by birkir** [comment]
No problem. ps. nice touch! 

Gangi þér vel vinur
